const commonActionTypes = {
  GET_ALL_CHARACTERS: 'GET_ALL_CHARACTERS',
  GET_ALL_CHARACTERS_SUCCESS: 'GET_ALL_CHARACTERS_SUCCESS',
  GET_ALL_CHARACTERS_FAIL: 'GET_ALL_CHARACTERS_FAIL',
  GET_CHARACTER_BY_NAME: 'GET_CHARACTER_BY_NAME',
  GET_CHARACTER_BY_NAME_SUCCESS: 'GET_CHARACTER_BY_NAME_SUCCESS',
  GET_CHARACTER_BY_NAME_FAIL: 'GET_CHARACTER_BY_NAME_FAIL'
}

export default commonActionTypes
