const commonActionTypes = {
  GET_ALL_CHARACTERS: 'GET_ALL_CHARACTERS',
  GET_ALL_CHARACTERS_SUCCESS: 'GET_ALL_CHARACTERS_SUCCESS',
  GET_ALL_CHARACTERS_FAIL: 'GET_ALL_CHARACTERS_FAIL',
  GET_CHARACTER_BY_NAME: 'GET_CHARACTER_BY_NAME',
  GET_CHARACTER_BY_NAME_SUCCESS: 'GET_CHARACTER_BY_NAME_SUCCESS',
  GET_CHARACTER_BY_NAME_FAIL: 'GET_CHARACTER_BY_NAME_FAIL',
  GET_CHARACTER_BY_SPECIES: 'GET_CHARACTER_BY_SPECIES',
  GET_CHARACTER_BY_SPECIES_SUCCESS: 'GET_CHARACTER_BY_SPECIES_SUCCESS',
  GET_CHARACTER_BY_SPECIES_FAIL: 'GET_CHARACTER_BY_SPECIES_FAIL',
  CLEAR_ALL_CHARACTERS: 'CLEAR_ALL_CHARACTERS',
  GET_EPISODES: 'GET_EPISODES',
  GET_EPISODES_SUCCESS: 'GET_EPISODES_SUCCESS',
  GET_EPISODES_FAIL: 'GET_EPISODES_FAIL',
  SET_PAGE: 'SET_PAGE',
  SET_CHARACTER_NAME: 'SET_CHARACTER_NAME'
}

export default commonActionTypes
