const commonActionTypes = {
  GET_ALL_CHARACTERS: 'GET_ALL_CHARACTERS',
  GET_ALL_CHARACTERS_SUCCESS: 'GET_ALL_CHARACTERS_SUCCESS',
  GET_ALL_CHARACTERS_FAIL: 'GET_ALL_CHARACTERS_FAIL'
}

export default commonActionTypes
